version: '3.1'
services:
  db:
    image: mysql
    container_name: simple_todo_list_mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
    - "3306:3306"
    volumes:
    - lindolfo_data:/var/lib/mysql
volumes:
  lindolfo_data: