INSERT INTO TASK (task, complete) VALUES ('Cozinhar', true)
INSERT INTO TASK (task, complete) VALUES ('Correr', false)
INSERT INTO TASK (task, complete) VALUES ('Lavar louça', true)
INSERT INTO TASK (task, complete) VALUES ('Estudar', true)
INSERT INTO TASK (task, complete) VALUES ('Viajar', true)
INSERT INTO TASK (task, complete) VALUES ('Estudar Exessões', false)
INSERT INTO TASK (task, complete) VALUES ('Estudar Testes Unitários', false)
INSERT INTO TASK (task, complete) VALUES ('Dormir', false)
INSERT INTO TASK (task, complete) VALUES ('Fazer prova', false)
INSERT INTO TASK (task, complete) VALUES ('Ir pra faculdade', false)